### ISSUE TITLE
schema with $ref

### ISSUE THREAD

**Issue by lstkz** [mohsen1/json-schema-view#19]
It is possible to use schemas that contain a `$ref` field?

**Comment by mohsen1** [comment]
I recommend resolving the references before passing it to this directive.

**Comment by rbren** [comment]
I have a fork that allows for local $refs:
https://github.com/bobby-brennan/json-schema-view

See this PR for instructions:
https://github.com/mohsen1/json-schema-view/pull/21

Since $refs can be circular, resolving them prior to using this directive can be problematic. Instead, I resolve $refs inside the json-schema-view directive only when isCollapsed = false.  That way they can be resolved on-demand as the user explores the object.
